name: Temporary export data rebase base
on:
  push:
    branches:
      - feature/interrogative-working
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: tar --exclude=.git -czf /tmp/kotomi-data-main.tar.gz .
      - uses: actions/upload-artifact@v4
        with:
          name: kotomi-data-main-rebase
          path: /tmp/kotomi-data-main.tar.gz
