name: Validate Content update test
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 tools/validate_repository.py
